### ISSUE TITLE
Requirements for building

### ISSUE THREAD

**Issue by arnowelzel** [strukturag/nextcloud-spreed-signaling#12]
I just tried to clone and build the signaling server in Ubuntu 18.04 and found out there are at least to requirements which need to be installed first:

- golang
- curl

Maybe this should be added to the readme.

**Comment by morph027** [comment]
Another way is leveraging docker for the builds ;)

https://github.com/strukturag/nextcloud-spreed-signaling/issues/4#issuecomment-630982439

**Comment by denisj07** [comment]
Also python3 should be installed (was using centos 8, which does not include python3 per default)

**Comment by peacepenguin** [comment]
This is an open source application now, so all elements you see are eligible for community contributions. You yourself can actually update the Readme and documentation to be accurate and current according to your findings:

Fork the code in github to your own editable copy - edit the Readme in your forked repo with your updates, then create a pull request to get the changes merged into the main repo.

Documentation updates usually can be approved quickly since there's no testing needed like there is for code changes.

As a developer, the "work" is already done if you do all that, so there's generally no barrier to the improvement. Whereas an issue request like this might linger because the dev seeing it has to go make all the changes themselves and commit them instead of simply approve a pending merge request created by the community.

Check here for some basics on the github workflow so you can get involved with improving this project directly, open source only works if everyone that finds these issues helps to fix them too! Lets prove that @strukturag made a good decision in open sourcing this app by giving them code and documentation updates that improve the product for their customers and open-source users alike!

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository

**Comment by morph027** [comment]
See https://github.com/strukturag/nextcloud-spreed-signaling/pull/14
