### ISSUE TITLE
SIP bridge

### ISSUE THREAD

**Issue by flo-wer** [strukturag/nextcloud-spreed-signaling#23]
Is there any or can you provide any information on whether the now open source High Performance Backend can work as a SIP bridge?

According to several issues in the Nextcloud Talk repository (nextcloud/spreed#1604, nextcloud/spreed#1605, nextcloud/spreed#1606, nextcloud/spreed#1607, nextcloud/spreed#1608, nextcloud/spreed#2511, nextcloud/spreed#2512), especially:

> [...] the SIP bridge is part of the Nextcloud Talk High Performance Back end [...]
https://github.com/nextcloud/spreed/issues/2512#issuecomment-563940418

this is possible with the closed source version.

**Comment by peacepenguin** [comment]
I don't think the HPBE really does anything with SIP at all. But because the HPBE is built on/leverages the Janus WebRTC gateway for its actual A/V handling, it could be as easy as configuring Janus SIP integration per the Janus SIP plugin docs here:

https://janus.conf.meetecho.com/docs/sip.html

I have a plan to investigate and implement SIP/PSTN functionality in the open source HPBE, this SIP Plugin for Janus is where my research has led so far as the most likely integration point for SIP functionality.

Because SIP integration is a key selling point for the commercial offering, don't be too surprised if we, the community, needs to find a method to do this ourselves outside the way the commercial offering provides it. Although that should be avoided if possible, it is sometimes an inevitability with commercial products that are also open-source code based.

**Comment by fancycode** [comment]
The SIP integration is a separate component of the commercial Talk offering. It connects to the signaling server / Janus like a regular client in a Talk room.

Unfortunately there are currently no plans to open-source that component.

**Comment by flo-wer** [comment]
Thanks for your replies.

@fancycode Would you accept contributions to the Open-Source version that implement SIP bridge features? Also is it possible to publish any interfaces currently used by the Closed-Source version, so additions developed by the community can reuse them and are compatible with any planed Nextcloud features (see linked issues)? Especially as the aforementioned issues talk about settings inside Nextcloud to configure phone numbers, PINs, etc.

@peacepenguin I also did some research into Janus and other projects using it for SIP integration and from reading the documentation at [[1]](https://janus.conf.meetecho.com/docs/sip.html)[[2]](https://janus.conf.meetecho.com/docs/videoroom.html), I think it should be a reasonable amount of work to get calling into a room working.

From what I understand, the HPBE has to be extended to understand the requests from the SIP plugin for receiving calls. It then forwards the JSEP offer to the VideoRoom plugin that handles the conference rooms. Sending calls out seems not possible because both Plugins need a JSEP offer to create a connection.

The intended flow to accept a new call should be:  [SIP plugin] `register` -> [SIP plugin] `incomingcall` -> JSEP offer -> [VideoRoom plugin] `join` & `publish` (with JSEP offer) -> JSEP answer -> [SIP plugin] `accept` (with JSEP answer)

Another problem is asking for the room number. Additional numbers typed in are handled by the dtmf_info request, but this only applies to outgoing calls, not incoming calls. From studying some SIP standards, this could be accomplished following [this RFC](https://tools.ietf.org/html/draft-kaplan-dispatch-info-dtmf-package-00), i.e. in Janus it is received using `info` events.

**Comment by fancycode** [comment]
@flo-wer There is not a special "closed source" version of the signaling server that is used for the SIP bridge. The SIP bridge is a separate application that communicates with the regular signaling server.

I would rather avoid adding any media processing code to the signaling server. This would be required for the SIP bridge, which does audio mixing (among other things).
