### ISSUE TITLE
Could not send request : context deadline exceeded

### ISSUE THREAD

**Issue by violoncelloCH** [strukturag/nextcloud-spreed-signaling#298]
I'm getting this error in the signaling server log and endless connection retries on the client:
```
client.go:282: Client from 172.16.0.20:57406 has RTT of 119 ms (119.3209ms)
backend_client.go:160: Could not send request {"type":"auth","auth":{"version":"1.0","params":{"userid":"ncuser","ticket":"jp1FGjo2QocVBcaY:1657790674:ncuser:7401c814f6c60b218a3ddbe3186648a88d391cccf5c68626c534b79792cdf26e"}}} to https://cloud.example.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend: Post "https://cloud.example.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend": context deadline exceeded
```

The weird thing is that I've the exact same signaling server working with other Nextcloud instances (all configured as individual backends in server.conf). However requests from the signaling server to that uri returns the same for all nextcloud instance?
```
# curl https://cloud.example.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend
{"message":"CSRF check failed"}%
```
```
# curl -H "OCS-APIRequest: true" https://cloud.example.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>400</statuscode>
  <message/>
 </meta>
 <data>Internal signaling disabled.</data>
</ocs>
```
where cloud.example.com is the domain of the corresponding Nextcloud instance; response is the same for all of them.

Any idea where this problem might be coming from ?

Signaling server version: v0.5.0
Nextcloud Talk app version: 14.0.3

**Comment by fancycode** [comment]
This backend request from the signaling server to Nextcloud will perform some (database) operations and thus might take longer than the configured timeout:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/dcc583736a4f318adab9890deef94c20edebf98e/server.conf.in#L95

Can you see the request in your webserver log or see any entries in `nextcloud.log` at the time this happens? However most of the time such issues are caused by a firewall between the signaling server and the Nextcloud webserver.

**Comment by violoncelloCH** [comment]
Thanks !
This was indeed the issue (the Nextcloud server runs on some really old hardware, so I assume it's just database queries taking some more time than 10s); so raising the timeout mitigated the issue...
