### ISSUE TITLE
Signaling Server Connectivity issue

### ISSUE THREAD

**Issue by dolphinscorp** [strukturag/nextcloud-spreed-signaling#378]
Hi

I have configured nextcloud-spreed-signaling, On first time when we configured signaling in Web UI Admin of Nextcloud signaling it was working fine, due to some reason, we just deleted signaling url from Nextcloud and after few hour add it again then we are getting this error :
 Capabilities expired for https://mydomain.com/ocs/v2.php/cloud/capabilities,
Dec 10 09:07:45 backup-sso signaling[174888]: backend_client.go:164: Could not send request {"type":"auth","auth":{"version":"1.0","params":{"userid":"User01","ticket":"XXvLPHkrFNBIyJQp:1670662834:User01:c2986a132bc6781adfd0b7e2a690c2de2d48b5c0686a8a61f947580d22e87b67"}}} to https://mydomain.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend: Post "https://mydomain.cloud/ocs/v2.php/apps/spreed/api/v3/signaling/backend": context deadline exceeded
server.conf:
![image](https://user-images.githubusercontent.com/115947558/206842630-e64a6efc-3111-4b90-98a7-9603cb723384.png)

![image](https://user-images.githubusercontent.com/115947558/206842694-1bbc6da0-c7bc-4f2d-97d9-ffdcce584781.png)

![image](https://user-images.githubusercontent.com/115947558/206842708-fac518da-ed54-46dd-b040-4e3f51e30d57.png)

![image](https://user-images.githubusercontent.com/115947558/206842775-e037378f-95c7-4e1f-8641-633bba007ed1.png)

Pleasee suggest

**Comment by Speed7811** [comment]
Hi,

I have the same situation here. I configured exactly like this guide: https://www.c-rieger.de/nextcloud-hub-3-talk-signaling-server/

First time I start all services and entered the URL + Secret in the Admin UI of nextcloud => All test ok. I want to test if it works with a wrong secret and changed it in Nextcloud -> Test ok -> nothing works.

After this I changed the secret back to the old one and I got not this message over and over again:

`
client.go:282: Client from 91.248.117.47 has RTT of 17 ms (17.445615ms)
backend_client.go:164: Could not send request {"type":"auth","auth":{"version":"1.0","params":{"userid":"doepke","ticket":"bi+PB8kAjxYYjRml:1671142992:doepke:cfd78630af3a289ceb194ccb92ba6b76ed0fe3598eb1e6347860fecc7bdbd61e"}}} to https://cloud.mycompany.de/ocs/v2.php/apps/spreed/api/v3/signaling/backend: Post "https://cloud.mycompany.de/ocs/v2.php/apps/spreed/api/v3/signaling/backend": context deadline exceeded
client.go:282: Client from 91.248.117.47 has RTT of 19 ms (19.079624ms)
`

I checked the secret more than one time in Nextcloud and on my signaling server. Nothing works...

Can anybody give us a tip what the cause is?

Best regards

Rainer

**Comment by Speed7811** [comment]
Hey,

ok sometimes the solution is so simple. In my case it was the bruteforce detection of Nextcloud. I read this in the [issue 378](https://github.com/strukturag/nextcloud-spreed-signaling/issues/378). 

I deactivated (for testing) fail2ban (but this was not the reason) and the Nextcloud bruteforce (https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html) and restarted my webserver => That works now :) 

First I check the brute force attemps in the database: SELECT * FROM oc_bruteforce_attempts;

I will try to whitelist the signaling IP now. Maybe this helps you!

Best regards

Rainer

**Comment by dolphinscorp** [comment]
Thank you, i will try this. I remember, in nextcloud security setting in Admin panel there is option to whitelist IPs, i will try that and update here

**Comment by fancycode** [comment]
See #332
