### ISSUE TITLE
Allow using peer-to-peer instead of Janus for one-on-one converations

### ISSUE THREAD

**Issue by normen** [strukturag/nextcloud-spreed-signaling#804]
Hi,

it might make sense to have an option to bypass using a configured Janus server for one-on-one conversations and fall back to peer-to-peer. The advantages of using the Janus bridge are probably only getting relevant for larger meetings with more people.

Thanks for this software!

**Comment by fancycode** [comment]
This is probably something that should be configurable in Nextcloud Talk, not the signaling server itself.

Please open an issue in the Talk repository (https://github.com/nextcloud/spreed/issues/new/choose) and feel free to refer to this issue here.

Besides: having a central server for the WebRTC part could help participants that might not be able to connect to each other otherwise.

**Comment by normen** [comment]
> Please open an issue in the Talk repository (https://github.com/nextcloud/spreed/issues/new/choose) and feel free to refer to this issue here.

Did that, lets see what the response is: https://github.com/nextcloud/spreed/issues/13148

> Besides: having a central server for the WebRTC part could help participants that might not be able to connect to each other otherwise.

Sure but that would be exactly what the TURN server is for, which only makes a relay connection when really needed, too.
